[package]
name = "nocap"
version = "0.1.0"
authors = ["Eric Warburg <edwarburg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.4.0"
scopeguard = "1.1.0"
itertools = "0.10.0"